project:
  type: website
  output-dir: docs

website:
  title: "Projects_Reports"
  navbar:
    left:
      - href: index.qmd
        text: Reports

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



